reflex-frp/reflex

reflex.cabal
This builds for me on GHC 7.8.2
=> Allow lens-4.8

bench/Main.hs, reflex.cabal
Some of the benchmarks don't make much sense yet (for example, it doesn't make sense to benchmark subscribing by running it multiple times)
=> WIP: Add some micro benchmarks for spider

reflex.cabal
=> Primitive 0.6

src/Reflex/Spider/Internal.hs
This improves type-safety, because it's no longer possible to forget a subscribeEvent now. 
Previously, passing an Event to readEvent without subscribing it first was possible without getting a type error.
=> Make EventHandle a newtype in Spider

src/Reflex/Dynamic.hs
Let me know your comments. Like if the haddock doc is too long or the type sig should be inline.
=> Add apDyn to enable applicative style programming on Dynamic

bench/Main.hs, reflex.cabal, test/Reflex/Bench/Focused.hs, test/Reflex/Plan/Pure.hs, test/Reflex/Plan/Reflex.hs, test/Reflex/Pure.hs, test/Reflex/Test.hs, test/Reflex/Test/Micro.hs, test/Reflex/Test/RunAll.hs, test/Reflex/TestPlan.hs
- Add set of tests I'd written using generalization of the CrossImpl  (includes all the old ones plus quite a few newer ones)
- Updates the benchmarks to include some refactoring and also a few new ones (notably some benchmarks for fans)
=> Update benchmarks and add tests

Quickref.md
adding Behavior-of-Behavior flattening docs to quickref
=> Flattening docs

reflex.cabal, src/Reflex/Class.hs
This adds the following instances:
* `Behavior`:
* `Apply`
* `Bind`
* `Fractional`
* `IsString`
* `Num`
* `Event`:
* `Alt`
* `Apply`
* `Bind`
* `Extend`
* `Plus`
=> More instances for `Behavior` and `Event`

src/Reflex/Class.hs
These additions follow a common pattern for splitting a single event in two based on the inner type of the value. I believe they will reduce a lot of future boilerplate and set a standard practice for splitting events that can contain multiple types.
=> Add Either and These event-splitting functions.

reflex.cabal, src/Reflex/Class.hs
Here's a pull request for issue #72.  I wasn't sure if anything was needed in Spider.Internal, but GHC is happy with this so it seems not.
=> Add Default instance for Dynamic

src/Reflex/Spider/Internal.hs
Not sure how this is building in reflex-platform but this commit allows reflex to build standalone with the nix command:
```sh
nix-build -E "with (import <nixpkgs> {}); pkgs.haskell.packages.ghcjs.callPackage ./default.nix {}"
```
=> removed stray bang pattern

reflex.cabal, src/Reflex.hs, src/Reflex/EventWriter.hs, src/Reflex/Requester/Base.hs, test/EventWriterT.hs, test/RequesterT.hs
I haven't had the chance to test this code yet (I have only proved it correct with GHC :P).  But I wanted to get it up to start discussion.
=> Add EventWriter

src/Reflex/Class.hs
Btw. do you have any code at hand making use of Incrementals, I get a feeling it could help simplify some code of mine, but a usage example would really help.
=> Clarify difference between Incremental and Dynamic

src/Reflex/Patch.hs
=> Fix unused import warning

default.nix, reflex.cabal, src/Reflex/Dynamic/TH.hs, src/Reflex/Patch.hs, src/Reflex/Spider/Internal.hs, test/GC.hs, test/Reflex/Test/CrossImpl.hs
Also fixes for hlint and tell nix to ignore `dist` directory
=> haskell-src-exts 1.18 support

src/Reflex/Class.hs
This is useful for combining several Behaviors or Dynamics
together and sampling them with an Event.
There is an example in the Haddocks for the typeclass that
might help explain further / motivate the addition.
=> Adds the `AttachApply` typeclass.

reflex.cabal
To correct build failure https://travis-ci.org/reflex-frp/reflex/jobs/278979651
=> Make QueryT tests dependent on semigroups

.travis.yml
Build failing at https://travis-ci.org/reflex-frp/reflex/jobs/279012295
https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/compilers/ghc
=> Move Travis to 8.2.1

src/Reflex/Class.hs
=> Added IsString instance for Dynamic

.travis.yml, default.nix, reflex.cabal, src/Reflex/Class.hs, src/Reflex/Time.hs
I haven't tested this yet, but I'm pushing what I have so that I don't forget that I have it a branch somewhere. There is a companion PR for `reflex-dom` [here](https://github.com/reflex-frp/reflex-dom/pull/168).
=> Brings in the Time module from `reflex-dom`

Quickref.md
Some of the new content came from the QuickRef.md in the `reflex-dom` repository, which has been removed in a [companion PR](https://github.com/reflex-frp/reflex-dom/pull/177).
=> Adjusts Quickref.md to reflect recent changes

src/Reflex/PerformEvent/Base.hs, src/Reflex/PostBuild/Base.hs, src/Reflex/Query/Base.hs, src/Reflex/Requester/Base.hs, src/Reflex/TriggerEvent/Base.hs
=> Add Monoid and Semigroup instances

src/Reflex/Time.hs
@cgibbard was too lazy to make a PR so I'm doing it with his code.
=> Reflex.Time: Add throttle

src/Reflex/Time.hs
Also adds documentation for the arguments to tickLossyFrom.
=> Reflex.Time: add tickLossyFromPostBuildTime

src/Reflex/Patch/DMapWithMove.hs
in my last PR, I used the `-- ^` syntax with a GADT constructor and haddock doesn't like that.
=> fix haddock failure in PatchDMapWithMove

src/Reflex/DynamicWriter/Base.hs, src/Reflex/EventWriter/Base.hs, src/Reflex/Host/Class.hs, src/Reflex/PostBuild/Base.hs, src/Reflex/Profiled.hs, src/Reflex/Query/Base.hs, src/Reflex/Spider/SpiderTimelineHost.include.hs, src/Reflex/TriggerEvent/Base.hs
These will needs some checking, and there are a few more to go that seem a bit tricky.
We're also missing a `newEventKeyHost` in the Spider, which we'll need to take care of.
=> Adds some more implementations of `newFanThing` / `newEventKeyHost`.

reflex.cabal, src/Reflex.hs, src/Reflex/Adjustable/Class.hs, src/Reflex/Class.hs, src/Reflex/Collection.hs, src/Reflex/DynamicWriter/Base.hs, src/Reflex/EventWriter/Base.hs, src/Reflex/Network.hs, src/Reflex/PerformEvent/Base.hs, src/Reflex/PostBuild/Base.hs, src/Reflex/Query/Base.hs, src/Reflex/Requester/Base.hs, src/Reflex/TriggerEvent/Base.hs, src/Reflex/Widget/Basic.hs, src/Reflex/Workflow.hs
Continues PR #121 from @dalaing. Ryan deemed the breakage acceptable. @ElvishJerricco I'll rebase this on top of your PR if that gets merged first. (And indeed it makes sense to do non-breaking first.)
=> Dedup adjustable

src/Reflex/Query/Base.hs
=> Add traverseIntMapWithKeyWithAdjust for QueryT

src/Reflex/DynamicWriter/Base.hs, src/Reflex/Query/Base.hs
=> Add MonadDynamicWriter for QueryT and MonadQuery for DynamicWriterT

src/Reflex/Adjustable/Class.hs
This is related to #208. However, unlike that hypothetical default, this shouldn't have any serious performance concerns as far as I'm aware.
=> Add default for traverseDMapWithKeyWithAdjust in terms of traverseDMapWithKeyWithAdjustWithMove

src/Reflex/Patch/MapWithMove.hs
This is a trivial generalization of `patchThatChangesAndSortsMapWith` that doesn't do the sorting and allows the user to do it however they want.
=> Generalize patchThatChangesAndSortsMapWith

reflex.cabal, src/Reflex/Class.hs, src/Reflex/EventWriter/Base.hs, src/Reflex/FunctorMaybe.hs, test/EventWriterT.hs
This fixes #234 and adds a test to prevent regression on #206.
=> Fix traverse* Adjustable methods in EventWriterT 

src/Reflex/DynamicWriter/Base.hs, src/Reflex/EventWriter/Base.hs
=> Give [Event|Dynamic]Writer instances of each other

Quickref.md
I use these functions frequently, and they seem underdocumented
=> add Reflex.Network documentation to Quickref.md

src/Reflex/Collection.hs
This is one module that most reflex users should probably skim through. The Collection functions are extremely important in any nontrivial reflex app. It was pretty hard to read, so I just ran [brittany](https://github.com/lspitzner/brittany/) over it and used haskell-mode in emacs for the comments.
=> Format the Collection module

Quickref.md
DMap has had two parameters for a while.
=> Update the types of merge and fan

src/Reflex/Requester/Base.hs
=> Add withRequesterT

src/Data/AppendMap.hs, src/Data/Functor/Misc.hs, src/Reflex/Class.hs, src/Reflex/Collection.hs, src/Reflex/Dynamic.hs, src/Reflex/Dynamic/TH.hs, src/Reflex/DynamicWriter/Base.hs, src/Reflex/FastWeak.hs, src/Reflex/FunctorMaybe.hs, src/Reflex/Network.hs, src/Reflex/NotReady/Class.hs, src/Reflex/Optimizer.hs, src/Reflex/Patch.hs, src/Reflex/Patch/Class.hs, src/Reflex/Profiled.hs, src/Reflex/Pure.hs, src/Reflex/Query/Class.hs, src/Reflex/Spider.hs, src/Reflex/Time.hs, src/Reflex/Workflow.hs
This should be merged after #284 
I only removed deprecated items that were deprecated over a year ago (mostly 2-3 years ago).
=> Cleanup and delete long-deprecated things

reflex.cabal, test/RequesterT.hs
These tests fail, not sure why requesterDataToList returns things in reverse order
=> Make RequesterT tests build again

ChangeLog.md, default.nix, reflex.cabal, src/Reflex/Pure.hs
Augment missed changelog entries, add some missed version bounds
=> Fix merges

.travis.yml, cabal.project.freeze
=> Add freeze file to avoid text 1.2.4.0 

ChangeLog.md, src/Reflex/Query/Base.hs
(cherry picked from commit 196cb7e1666b12acb457fa1f129b9f55dc924e3a +
changelog)
=> Add mapQueryT

ChangeLog.md
Not an interface change, but still notable.
=> Add changelog entry for 8.8 support

ChangeLog.md, src/Reflex/Query/Class.hs
=> MonadQuery: Add (Monad m) superclass constraint

src/Reflex/Class.hs
=> Unzip instance for Event

ChangeLog.md, src/Reflex/Dynamic.hs
One more change can make it in.
=> Update release candidate 0.7.1.0

reflex.cabal, src/Reflex/BehaviorWriter/Base.hs, src/Reflex/DynamicWriter/Base.hs, src/Reflex/EventWriter/Base.hs, src/Reflex/Query/Base.hs, src/Reflex/Requester/Base.hs
I also cleaned up some `MonadTrans` instances that can be derived, since it's closely related to `MFunctor`.
=> Add mmorph MFunctor instances
