- src/Reflex/Spider/Internal.hs
Hide the constructors of values pointed to by weak references behind a
NOINLINE function, or GHC will fuse the construction and
destruction (after some inlining), eliminating the constructor and thus
making the weak reference invalid.
I tested this with examples/host.hs, my own small example which forks a 
thread to trigger a timer event (to check clean up) and reflex-todomvc (native).
Didn't test this on GHCJS though.
> Hide constructors of values with weak pointers

- src/Reflex/Host/Class.hs
- src/Reflex/Spider/Internal.hs
This PR adds missing superclasses, docs for all functions in the Reflex.Host.Class 
module and some missing instances for mtl transformer types.
> Improvements for ReflexHost

- test/Reflex/Pure.hs
Is it necessary to use `memo` in the pure implementation?
> instanceSigs

- src/Reflex/Host/Class.hs
Really only needed the MonadReflexCreateTrigger which keeps hanging around as an orphan instance in my code, but the others were there so added them too.
> Add instances for strict StateT

- README.md
I thought it might be nice to have a link to the hackage package. Especially since it contains API documentation.
> Add link to reflex hackage package

- src/Reflex/Dynamic.hs
As I'm very new to reflex, this may be a bad idea for reasons I don't understand. However, in my usage so far, such an instance would have been convenient (as an alternative to `y <- mapDyn f x`).
> Functor instance for Dynamic

- src/Reflex/Dynamic/TH.hs
I don't know if Template Haskell has a better solution to this problem, but this at least keeps people from
stumbling over dyn.
> Change the variable name used when generating mkDyn expressions to something far less likely to capture.

- src/Reflex/Class.hs
justThis and justThat produce Nothing in the 'These' case, so neither event produced by fanThese would fire when the value of the event is a 'These', exactly the opposite of what I intended.
> Fix error with 'fanThese'.

- src/Reflex/Dynamic.hs
I've found `distributeListOverDynPure` to be a very useful function that is non-trivial to write. I think it would be a good addition to `distributeDMapOverDynPure` and `distributeMapOverDynPure`. The latter was not exported and documented strangely (possibly a copy-paste error), so I exported it and updated the documentation.
> Add distributeListOverDynPure, export distributeMapOverDynPure

- reflex.cabal
- src/Reflex.hs
- src/Reflex/Base.hs
- src/Reflex/DynamicWriter.hs
- src/Reflex/PerformEvent/Base.hs
- src/Reflex/PerformEvent/Class.hs
- src/Reflex/PostBuild/Class.hs
- src/Reflex/TriggerEvent/Base.hs
- src/Reflex/TriggerEvent/Class.hs
This pull request adds a base monad `ReflexBase` capable of most of the functionality offered by the various Reflex typeclasses. In particular, it uses `PerformEventT` and `PostBuildT` to enable their corresponding typeclasses, and it uses a new `TriggerEventT` monad transformer for the `TriggerEvent` class. The motivation of this pull request is to enable users of `reflex` to write reactive programs in contexts other than web apps with the same relative ease. Having one monad with these three main classes on top of `SpiderHost` covers a large surface area of requirements.
`TriggerEventT` was factored out of `ImmediateDomBuilder` from `reflex-dom`. As such, much of the `Widget` monad can be replaced with `ReflexBase`. This includes most of the implementation of `attachWidget`, which was …
> Added a base monad capable of `PerformEvent`, `PostBuild`, and `TriggerEvent`

- .travis.yml
Travis now builds. This pr removes support for ghc 7.8.4 but adds support for ghcjs! The travis file is also significantly easier to read.
> Move travis to use nix.

- src/Reflex/Class.hs
Thanks to @luigy for pointing this out.
> Fixes a typo in the docs for `<@>`.

- reflex.cabal
- src/Reflex/Widget/Basic.hs
Fixes #113
Also I'm curious if it'd be worth providing a version of this that accepts `Dynamic t (Map k v)` and handles inserts and deletes as well.
> Add a widget module; add fast sortable list widget

- reflex.cabal
- src/Data/AppendMap.hs
- src/Data/Functor/Misc.hs
- src/Reflex/Dynamic.hs
- src/Reflex/EventWriter.hs
We should be able to retain support for older GHCs a bit longer this way. (But see issue 99 for another problem facing 7.10.x.)
> Eliminate the only use of TypeApplications

- default.nix
- reflex.cabal
- src/Reflex/Query/Base.hs
- test/EventWriterT.hs
- test/QueryT.hs
- test/RequesterT.hs
- test/Test/Run.hs
- test/hlint.hs
- QueryT had a bug with runWithReplace where changing query at the same time as changing a child widget brought the app to an inconsistent state.
- hlint tests were broken, possibly by type applications being unsupported by hs source extensions, so the hlist test was improved so that we can mark modules as exceptions
- the tests for QueryT were similar to, but a little more complicated than the tests for RequesterT and EventWriterT, so a common apparatus for running all the tests was developed which will improve code reuse for future semantic tests.
> Fix a QueryT bug and along the way improve the test infrastructure

- reflex.cabal
- test/QueryT.hs
Tests run successfully on hlint 2.0.9 (currently in nixpkgs) so the bound does not seem necessary.
> remove hlint bound

- src/Reflex/Class.hs
I'm seeing variants of this all over the place. What do you think about adding it as a convenience? Do you think instead we should have corresponding `fmapLeft` and `fmapRight`, as I've seen both in a number of places, but `Right` is more common.
> Add convenience function fmapEither

- reflex.cabal
- src/Data/Map/Misc.hs
- src/Reflex.hs
- src/Reflex/Adjustable/Class.hs
- src/Reflex/Class.hs
- src/Reflex/Collection.hs
- src/Reflex/DynamicWriter.hs
- src/Reflex/EventWriter.hs
- src/Reflex/PerformEvent/Base.hs
- src/Reflex/PostBuild/Base.hs
- src/Reflex/Query/Base.hs
- src/Reflex/Requester/Base.hs
- src/Reflex/TriggerEvent/Base.hs
- src/Reflex/Widget/Basic.hs
- test/EventWriterT.hs
- test/QueryT.hs
- test/RequesterT.hs
This also brings the collection management functions across from `reflex-dom` - there is a companion PR in `reflex-dom` dealing with this [here](https://github.com/reflex-frp/reflex-dom/pull/163).
> Renames MonadAdjust and moves it to its own module.

- reflex.cabal
The upper bound of `haskell-src-exts` prevented stack from resolving deps on nightly. This bumps the upper bound to include `1.19`, which seems to work.
> Relaxed haskell-src-exts upper bound for GHC 8.2.1

- reflex.cabal
- src/Reflex/Network.hs
- src/Reflex/NotReady/Class.hs
- src/Reflex/Spider/Internal.hs
- src/Reflex/Workflow.hs
This also included moving generalizations of `dyn` and `widgetHold` across from `reflex-dom` and breaking out a `NotReady` class from the `DomBuilder` class.
There is a companion PR in the `reflex-dom` repository [here](https://github.com/reflex-frp/reflex-dom/pull/178).
> Moves Workflow across from reflex-dom

- src/Reflex/Class.hs
Hi,
I've just been reading through documentation and found this. This patch is just a small fix for a typo in Reflex.Class.
> Fix doc for "switcher"

- Quickref.md
- src/Reflex/Class.hs
- src/Reflex/Dynamic.hs
- test/Reflex/Test/CrossImpl.hs
- test/Reflex/Test/Micro.hs
Create non-prompt counterparts, even though these helper functions are dramatically simpler, so that no one mistakenly thinks we are endorsing the prompt versions over their non-prompt equivalents. This is important because the "prompt" semantics are rarely needed, yet are much more difficult to use
correctly.
Also, rename `switchPromptly` and `switchPromptOnly` to `switchHold*`. This helpers show how they are far more related to each other (having identical types) than they are to plain `switch`.
One small downside of this change is that it obscures relationship between `switchPromptlyDyn` and `switchHoldDyn`. This is deemd worth it as the use of the `current` behavior to avoid holding really does make a semantic difference: Old inner events prior to the first outer event firing will …
> Steer people away from `switchPromptly*`

- src/Reflex/Class.hs
Untested, but it compiles and it is Haskell - so it has to be correct.
> Added Semigroup instance for Dynamic.

- src/Reflex/Spider/Internal.hs
I didn't change the implementation, but the instance head looked incorrect.
> NotReady: Fix Spider NotReady instance head

- src/Reflex/Time.hs
Getting this error when building haddocks:
```
src/Reflex/Time.hs:233:13: error:
parse error on input ‘-- * Immediate mode turns off, and the buffer is empty.’
```
> Fix haddock parse error

- src/Reflex/Patch/DMapWithMove.hs
Added `insertDMapKey`, `swapDMapKey`, and `patchDMapWithMove` (a safe constructor) to round out the functionality.
Added doc comments to round out the understanding.
And finally found that `validPatchDMapWithMove` falsely claimed some valid patches were invalid, e.g. `moveDMapKey`, so I rewrote it. I rewrote it mostly because I wasn't clever enough to understand what the old one was getting at and was wrong, feel free to rewrite it. I also had it report what was wrong.
These are the patches I tested against `validPatchDMapWithMove`:
```haskell
p,p',p2,p3,s,p4,p4',p5,p5' :: PatchDMapWithMove MyTag Identity
p = moveDMapKey (MyInt "foo") (MyInt "bar")
p' = moveDMapKey (MyInt "bar") (MyInt "foo")
p2 = deleteDMapKey (MyInt "foo")
p3 = insertDMapKey (MyInt "foo") (Identity 444)
s = swapDMapKey …
```
> Some PatchDMapWithMove ergonomics improvements and doc comments

- src/Reflex/Adjustable/Class.hs
I managed to miss this somehow in some of my earlier functions.
These functions already exist in the `Reflex.Collection` module and are
exported from the `Reflex` module.
Fixes #188.
> Removes some redundant copies of the collection functions.

- src/Reflex/EventWriter/Base.hs
- test/EventWriterT.hs
Previously if the widget being replaced has a `tellEvent` which fires at the same time as the resulting ('replace finished') event returned from `runWithReplace`, the moribund widget's `tellEvent` will still count, potentially even at the same time as a new widget's `tellEvent`.
>  Fix Adjustable for EventWriterT with simultaneous replace and tell events

- Quickref.md
- src/Reflex/Class.hs
Intended to replace idioms like `ffor (zipDyn a b) $ \(a,b) -> (...)`.
I would've liked to add some more arities but `Control.Applicative` only exports up to 3.
We should only add higher arities for `ffor` if we also do for `liftA`.
> Add convenience functions: 'ffor2' & 'ffor3'

- src/Reflex/Profiled.hs
- src/Reflex/Spider/Internal.hs
Put the "deriving" clause on its own line for easier diffing, so we can make sure these don't get out of sync.
> Derive more newtype instances for ProfiledM

- src/Reflex/Optimizer.hs
Since base-4.9.0, Prelude exports `<>` and this creates an ambiguous occurrence wtih `GhcPlugins.<>`
> Hide <> from Prelude

- src/Reflex/Spider/Internal.hs
Hi, in part of our codebase at work we are performing `fmap (==k)` over many dynamics. @goolord and i thought it might be beneficial to write some rewrite rules to use demux, and wanted write some RULES like
```haskell
{-# RULES "fmapEqDynBecomesDemux" forall (k :: Bool) (d :: Dynamic Spider Bool). fmapDynamicSpider (== k) d = demuxed (demux d) k #-}
```
and we were going to benchmark it, just for curiousity. you can't use fmap on the LHS of a rewrite rule because typeclass methods usually inline so aggressively that fmap will inline before your rule can fire, and so your rule will never fire. the solution is to typically implement fmap in terms of another function, so that rules can use those functions (where you must specialise the functor, of course) in their LHS. This is what that PR …
> outsource dynamic spider's fmap

- src/Reflex/BehaviorWriter/Base.hs
these were reported to be redundant
> Hlint fixes

- test/QueryT.hs
Newer versions than 0.4.0.0 of monoidal-containers will include an align
instance, but it is not present in hackage yet.
> Fix build for QueryT test

- src/Data/FastWeakBag.hs
- src/Data/WeakBag.hs
- src/Reflex/Class.hs
- src/Reflex/Collection.hs
- src/Reflex/Dynamic.hs
- src/Reflex/Pure.hs
In the inlined code like `Dynamic t (Map k a)`, I have made it italic/emphasis. This is a bit unconventional, but increases the readability.
Its a surprise that haddock doesn"t allow inline code with backticks. The only thing it supports is monospaced text (inside @), but this appears almost similar to the plain text.
> Fixes for haddocks

- reflex.cabal
Reflex does not build with GHC 7.10 or below.
> Tighten base lower bound

- reflex.cabal
- src/Reflex/Patch/MapWithMove.hs
Fixes #270.
This passes `cabal new-test`, but has not been tested against ghcjs. I do not know how to update reflex-platform either, but this seems like a pretty safe change.
> Relax bounds on 'these', add explicit import to avoid clash

- src/Reflex/Requester/Base.hs
Useful when using RequesterT with a transport that doesn't automatically pair up requests and responses (e.g., websockets).
> Add matchResponsesWithRequests

- default.nix
- reflex.cabal
- src/Data/AppendMap.hs
- src/Reflex/Class.hs
- src/Reflex/FunctorMaybe.hs
- src/Reflex/Requester/Base.hs
- src/Reflex/Spider/Internal.hs
- src/Reflex/Time.hs
Deprecates FunctorMaybe.
The class is still re-exported by Reflex.Class and hence by Reflex, but the method fmapMaybe is not automatically re-exported (in favor of exporting a new fmapMaybe alias to mapMaybe from Filterable). This isn't ideal, as it'll still cause some breakage where instances were defined (I think).
> Deprecate FunctorMaybe in favor of Filterable

- ChangeLog.md
A preference of mine so that I see the most recent changes first when I open the file in GitHub, etc. When in a termal, I'd use `less` anyway. Feel free to close if you disagree.
> Use reverse chronological order in ChangeLog

- src/Reflex/Class.hs
- src/Reflex/Dynamic.hs
I used the code from distributeListOverDynPure as it is easier to understand.
> Mark distributeListOverDynPure as deprecated, remove duplication.

- src/Reflex/Class.hs
It appears that partial application for `fan` went away, but the haddock never changed (how can you partially apply a unary function?).
I have also removed the `TODO` comment, as it seemed no longer relevant. I can re-add it if required.
> fan: Rewrite haddock

- ChangeLog.md
- reflex.cabal
- src/Reflex/Class.hs
- src/Reflex/Profiled.hs
- src/Reflex/Pure.hs
- src/Reflex/Spider/Internal.hs
- test/GC.hs
Generalize types of merge methods.
> Generalize merge

- src/Reflex/Spider/Internal.hs
The previous code was struggling to create artificial dependencies
to prevent `unsafePerformIO` calls from being floated out of their
proper context. Push the context into each `unsafePerformIO` call
so the dependency is real. Reading a bit of the resulting Core,
I don't expect to see many (if any) performance regressions.
Performance will hopefully improve a bit if/when
[GHC issue 15127](https://gitlab.haskell.org/ghc/ghc/issues/15127)
is fixed.
> Better unsafe perform io

- reflex.cabal
- src/Control/Monad/ReaderIO.hs
- src/Reflex/Class.hs
- src/Reflex/Profiled.hs
- src/Reflex/Pure.hs
- src/Reflex/Spider/Internal.hs
- test/Reflex/Bench/Focused.hs
Get rid of most unnecessary uses of `unsafeCoerce`. Several of the ones that remain are removed by #320.
> Less unsafeCoerce

- src/Reflex/Class.hs
coincidence has worse complexity because it invalidates height
> Use align (a merge) instead of coincidence for <.>

- default.nix
The cabal file had for test suites, but not the `default.nix`.
> Add missing these-lens dep

- .travis.yml
- cabal.haskell-ci
- reflex.cabal
- release.nix
- src/Data/Functor/Misc.hs
- src/Reflex/Class.hs
- src/Reflex/Dynamic.hs
- src/Reflex/Spider/Internal.hs
Moves `fail` from `Monad` instances when using ghc 8.8.1
and instead includes `MonadFail` where `fail` is needed.
Fixes #377
> Fixes for ghc 8.8.1

- reflex.cabal
- test/Adjustable.hs
Reproduces bug in #369, so is disabled until the fix in #371 is merged.
> Add test suite for Adjustable

- test/Reflex/Test/CrossImpl.hs
This uses Reflex.Profiled in addition to Pure & Spider for testing.
Reflex.Profiled wraps Spider here, so that it most results should be
the same. However, this should help to catch early some bad bugs that
occasionally occur in Reflex.Profiled.
> Add Reflex.Profiled test for CrossImpl

- ChangeLog.md
- src/Reflex/BehaviorWriter/Base.hs
- src/Reflex/BehaviorWriter/Class.hs
For consistency with EventWriter/DynamicWriter classes.
----
#
> Rename MonadBehaviorWriter -> BehaviorWriter; deprecate old name

- ChangeLog.md
- src/Reflex/Profiled.hs
@mpickering asked me whether it was possible to use `Reflex.Profiled`
with `reflex-basic-host`. I said that it probably wouldn't be too
hard, you'd just need lifts here and there.
This PR adds lifting instances for all the classes I could find in
`reflex`, and tidies up a couple of warts I found along the way. I
don't really understand `Reflex.Profiled` (I just hit things with
`coerce` and `lift` until GHC was happy), so please look closely to
make sure useful things aren't getting dropped on the floor.
> Lifting instances for `Reflex.Profiled`

- src/Reflex/FastWeak.hs
- src/Reflex/Spider/Internal.hs
(Also move what I think is the corresponding comment)
Without this NOINLINE, the FastWeakTicket can be fused away (in
cacheSubscription in particular), causing early unsubscriptions.
This manifested itself in reflex-dom-core as items in a nested list
never being added to the DOM, because runWithReplace in the immediate
builder was being unsubscribed from the lifted runWithReplace result
events.
> Add NOINLINE pragma to mkFastWeakTicket

- reflex.cabal
- src/Reflex/Host/Headless.hs
This originally came from the reflex-ghci test suite, but it's more broadly useful.
> Add Reflex.Host.Headless

- src/Reflex/Host/Headless.hs
@meditans @ryantrinkle @3noch 
Not sure why this was controversial [in the headless PR](https://github.com/reflex-frp/reflex/pull/413#discussion_r418333059); it seemed straightforward in `reflex-basic-host`.
> Run each headless network on its own timeline

- ChangeLog.md
- src/Reflex/Class.hs
- src/Reflex/EventWriter/Base.hs
- src/Reflex/PerformEvent/Base.hs
- src/Reflex/PostBuild/Base.hs
- src/Reflex/Profiled.hs
- src/Reflex/Pure.hs
- src/Reflex/Spider/Internal.hs
- src/Reflex/TriggerEvent/Base.hs
- test/Reflex/Plan/Pure.hs
- test/Reflex/Test/Micro.hs
I hope the implementation in Spider is correct, it produced the expected result when testing with `switchHoldPromptly never . pushAlways (\a -> fmap (a <$) now)`.
Extending the Reflex class might break modules depending on Reflex if they or another dependency use `now` as an identifier. Let me know if that's not okay.
The change is motivated by distributed Reflex (coming soon™), in which
you can write things like:
```
roundTrip :: (...) => Location t -> m (Event t ())
roundTrip to = headE =<< perceptionsHere =<< perceptionsAt to =<< now
```
Maybe there are other use cases as well?
> Extend the Reflex class with `now :: PushM t (Event t ())`. (Issue #414)

- reflex.cabal
I have successfully build reflex with those dependencies in nixpkgs.
I would very much appreciate a hackage revision with these version bounds updated.
> Bump version bounds

- reflex.cabal
- src/Reflex/Adjustable/Class.hs
- src/Reflex/Class.hs
- src/Reflex/EventWriter/Base.hs
- src/Reflex/Profiled.hs
- src/Reflex/Pure.hs
- src/Reflex/Query/Base.hs
- src/Reflex/Requester/Base.hs
- src/Reflex/Spider/Internal.hs
- test/Reflex/Test/CrossImpl.hs
This haden‘t cropped up before because the version constraint in patch
prevent cabal from ever picking this dependent-map version
> Make build work with newest dependent-map

- Quickref.md
Only `alignEventWithMaybe` is exposed by [Reflex.Class module](https://github.com/reflex-frp/reflex/blob/develop/src/Reflex/Class.hs#L49). If `align` and `alignWith` were meant to be exposed that would be better fix, but I was looking to use them based on Quickref, and (unless I am missing something) this document is not reflecting what Reflex actually exposes for align functions. I was using reflex v0.63 brought in from reflex-platform v0.4.0.0, but it looks like adjacent versions are the same regarding this.
> Quickref update align function documentation 

- reflex.cabal
- src/Reflex/Host/Headless.hs
- test/Headless.hs
Don't enter the headless main loop if there's a shutdown request upon post build.
Without this check, if the application immediately requests shut down on a post build action, the application fails with a `thread blocked indefinitely in an MVar operation` instead of exiting gracefully.
An example use case is trying to read a file on post build, but failing as the file cannot be found. The application would handle this issue as it sees fit and immediately request exit, but fail to do so.
> fix: check on headless exit on post build

- reflex.cabal
This as an oversight in backporting the GHC 8.10 support.
> Mmorph shouldn't be needed yet

- .github/workflows/haskell.yml
- ChangeLog.md
- reflex.cabal
- Clean up GitHub action
- Complete change log
- Fix GHCJS tested version
- Bump base lower bound because we in fact do not build with 8.2 and earlier.
> Merge a few things in from v0.7.1.1

- src/Reflex/Dynamic/TH.hs
Instead of using the prone-to-breakage TH AST, use quoting and splicing.
> Avoid TH compat CPP

- src/Reflex/Requester/Base.hs
I noticed that RequesterT was missing this passthrough instance.
> Add EventWriter instance for RequesterT

- src/Reflex/Network.hs
* Replace reference to deprecated function with its replacement
* Normalise comment formatting
* Suggest how to flatten the result of `networkHold`
> Reflex.Network: improve haddocks

- reflex.cabal
Fixes CI which started failing recently since `text` 2.1.2 broke `proctest` build and thus a test suite here. 
`proctest` is not actually used here, only declared so easy fix.
https://github.com/haskell/text/pull/608
https://github.com/alexfmpe/reflex/actions/runs/11654426219/job/32447941922#step:5:948
```
Error:     Ambiguous occurrence ‘show’
It could refer to
either ‘Prelude.show’,
Error: cabal: Failed to build proctest-0.1.3.0. See the build log above for
details.
imported from ‘Prelude’ at Test/Proctest.hs:65:8-20
(and originally defined in ‘GHC.Show’)
or ‘Data.Text.show’,
imported from ‘Data.Text’ at Test/Proctest.hs:104:1-16
|
196 |     msg = "Test.Proctest.Timeout: " ++ show n ++ " microseconds do not fit into Int"
|                                        ^^^^
Error: Process …
```
> Remove unused proctest dependency
